#ifndef COLLIDER_REGISTRY_H
#define COLLIDER_REGISTRY_H

#include "MainDefinitions.h"

#define MAX_ACTIVE_COLLIDERS 20
#define MAX_COLLISION_CALLBACKS 4
#define MAX_COLLISION_STATE_BYTES (((MAX_ACTIVE_COLLIDERS * MAX_ACTIVE_COLLIDERS) + 7) / 8)

typedef enum {
    BOX_COLLIDER,
    NUM_COLLIDER
} ColliderType;


#endif
